plugins {
    id 'com.android.application'
}

android {
    namespace 'com.termux.apiextended'
    compileSdk 34

    defaultConfig {
        applicationId "com.termux.apiextended"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0.0-beta.1"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError true
        warningsAsErrors false
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core:1.12.0'
}
